# Generated by Django 5.2.10 on 2026-01-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="description",
            field=models.TextField(blank=True, help_text="公司簡介"),
        ),
        migrations.AddField(
            model_name="stock",
            name="eps",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="每股盈餘",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="market",
            field=models.CharField(
                choices=[("US", "美股"), ("TW", "台股")],
                default="US",
                help_text="市場別",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="pe_ratio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="本益比",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="sector",
            field=models.CharField(blank=True, help_text="產業類別", max_length=50),
        ),
        migrations.AlterField(
            model_name="stock",
            name="name",
            field=models.CharField(blank=True, help_text="公司名稱", max_length=100),
        ),
        migrations.AlterField(
            model_name="stock",
            name="ticker",
            field=models.CharField(
                help_text="股票代號，例如：2330.TW", max_length=15, unique=True
            ),
        ),
    ]
