# Generated by Django 5.2.10 on 2026-01-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_stock_description_stock_eps_stock_market_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="beta",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="貝塔值 (風險係數)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="dividend_yield",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="殖利率",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="market_cap",
            field=models.BigIntegerField(blank=True, help_text="市值", null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="price_to_book",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="股價淨值比",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="profit_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="淨利率",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="roe",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="股東權益報酬率",
                max_digits=10,
                null=True,
            ),
        ),
    ]
