# Generated by Django 5.2.10 on 2026-01-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stock_beta_stock_dividend_yield_stock_market_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='漲跌額', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='change_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='漲跌幅 (%)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='最新成交價', max_digits=10, null=True),
        ),
    ]
