# Generated by Django 5.2.10 on 2026-01-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_add_financials'),
        ('stocks', '0005_stock_change_stock_change_percent_stock_last_price'),
    ]

    operations = [
    ]
