# Generated by Django 5.2.10 on 2026-01-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_merge_20260116_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='debt_to_equity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='負債權益比', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='free_cash_flow',
            field=models.BigIntegerField(blank=True, help_text='自由現金流', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='gross_margin',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='毛利率', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='operating_margin',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='營業利益率', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='quick_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='速動比率', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='roa',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='資產報酬率', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='short_name',
            field=models.CharField(blank=True, help_text='中文簡稱', max_length=50),
        ),
    ]
