# Generated by Django 5.2.10 on 2026-01-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_stock_debt_to_equity_stock_free_cash_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='alert_message',
            field=models.TextField(blank=True, help_text='財務指標異常警示訊息'),
        ),
    ]
