# Generated by Django 5.2.10 on 2026-01-26 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_stock_alert_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=1000)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_date', models.DateTimeField(db_index=True)),
                ('sentiment', models.CharField(default='neutral', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='stocks.stock')),
            ],
            options={
                'ordering': ['-pub_date'],
                'indexes': [models.Index(fields=['stock', '-pub_date'], name='stocks_stoc_stock_i_adbe11_idx')],
            },
        ),
    ]
