# Generated by Django 5.2.10 on 2026-01-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_stocknews'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='報表期間結束日')),
                ('year', models.IntegerField(help_text='報表年份')),
                ('period', models.CharField(choices=[('Q1', '第一季'), ('Q2', '第二季'), ('Q3', '第三季'), ('Q4', '第四季'), ('FY', '全年')], help_text='報表期間', max_length=2)),
                ('revenue', models.BigIntegerField(blank=True, help_text='營業收入', null=True)),
                ('gross_profit', models.BigIntegerField(blank=True, help_text='營業毛利', null=True)),
                ('operating_income', models.BigIntegerField(blank=True, help_text='營業利益', null=True)),
                ('net_income', models.BigIntegerField(blank=True, help_text='本期淨利', null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, help_text='每股盈餘', max_digits=10, null=True)),
                ('data_source', models.CharField(choices=[('finmind', 'FinMind'), ('mops', 'MOPS 公開資訊站'), ('yfinance', 'Yahoo Finance'), ('sec_edgar', 'SEC EDGAR'), ('alpha_vantage', 'Alpha Vantage')], default='finmind', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='stocks.stock')),
            ],
            options={
                'ordering': ['-year', '-period'],
                'indexes': [models.Index(fields=['stock', '-year', '-period'], name='stocks_fina_stock_i_dff489_idx')],
                'unique_together': {('stock', 'year', 'period', 'data_source')},
            },
        ),
        migrations.CreateModel(
            name='StockIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='資料日期')),
                ('indicator_type', models.CharField(choices=[('leading', '領先指標'), ('lagging', '落後指標')], help_text='指標類型', max_length=10)),
                ('name', models.CharField(help_text='指標名稱（如 PE, PB, 融資餘額）', max_length=50)),
                ('value', models.DecimalField(decimal_places=4, help_text='指標數值', max_digits=20)),
                ('data_source', models.CharField(choices=[('finmind', 'FinMind'), ('twse', 'TWSE 證交所'), ('yfinance', 'Yahoo Finance'), ('sec_edgar', 'SEC EDGAR'), ('alpha_vantage', 'Alpha Vantage')], default='finmind', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'name', '-date'], name='stocks_stoc_stock_i_14733f_idx')],
                'unique_together': {('stock', 'date', 'name', 'data_source')},
            },
        ),
        migrations.CreateModel(
            name='StockRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='資料日期')),
                ('year', models.IntegerField(help_text='營收年份')),
                ('month', models.IntegerField(help_text='營收月份')),
                ('revenue', models.BigIntegerField(help_text='營收金額（元）')),
                ('yoy_growth', models.DecimalField(blank=True, decimal_places=4, help_text='年增率', max_digits=10, null=True)),
                ('mom_growth', models.DecimalField(blank=True, decimal_places=4, help_text='月增率', max_digits=10, null=True)),
                ('data_source', models.CharField(choices=[('finmind', 'FinMind'), ('mops', 'MOPS 公開資訊站'), ('twse', 'TWSE 證交所')], default='finmind', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='stocks.stock')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['stock', '-year', '-month'], name='stocks_stoc_stock_i_0942f4_idx')],
                'unique_together': {('stock', 'year', 'month', 'data_source')},
            },
        ),
    ]
